version: "3.5"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - default
    restart: unless-stopped

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres/postgres -user=postgres -password=changeme -connectRetries=60 migrate
    volumes:
      - ./src/backend/migrations:/flyway/sql
    depends_on:
      - postgres
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    logging:
      driver: "none"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - default
    restart: unless-stopped

  api:
    image: prawn-node
    build:
      context: .
      dockerfile: prawn-node.Dockerfile
    working_dir: /home/node/app
    volumes:
      - ./src/:/home/node/app/src/:delegated
      - ./tsconfig.json/:/home/node/app/tsconfig.json:delegated
    command: "npm run start"
    environment:
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    networks:
      - default

  frontend:
    image: prawn-node
    build:
      context: .
      dockerfile: prawn-node.Dockerfile
    working_dir: /home/node/app
    volumes:
      - ./src/:/home/node/app/src/:delegated
      - ./tsconfig.json/:/home/node/app/tsconfig.json:delegated
    command: "npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres:
  pgadmin:
